name: ib-dev
channels:
  - openeye
  - conda-forge
dependencies:
  - python

  - openff-toolkit =0.14.3
  - openff-qcsubmit =0.50.1
  - openmmforcefields
  - smirnoff-plugins =2023.08.0
  # espaloma =0.3
  - geometric =1

  - ipython
  - ipdb
  - pre-commit

  - openeye::openeye-toolkits
  - rich

  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly

  - pip:
    - git+https://github.com/mattwthompson/de-forcefields.git@periodic-nonperiodic-methods
